# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74de4b1d27848611facddde58cfa560ee0f29bc5917cb62f6c3248f916fa490d670615d11c6eef51c2bd6a7927f3acbe1f55032f0fbd4d495cb146a4834e21ad

test:
  secret_key_base: 34643de3bb69aca5d10408c36fc25f59ff59b2820708b02fb807da8c176f868dbf96e68b2241c5e924379472c3856d94889dff5dc20ae3eb079ab6cd7c6a6956

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
